version: '2'
services:
    edkmsrecipe-cassandra:
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/edkmsRecipe/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    edkmsrecipe-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=edkmsrecipe-cassandra
    edkmsrecipe-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: edkmsrecipe-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
