version: '2'
services:
    edkmscommon-app:
        image: edkmscommon
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=edkmscommon-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
    edkmscommon-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: edkmscommon-cassandra
    edkmscommon-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=edkmscommon-cassandra
    edkmscommon-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: edkmscommon-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
