version: '2'
services:
    edkmsbrand-app:
        image: edkmsbrand
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=edkmsbrand-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
    edkmsbrand-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: edkmsbrand-cassandra
    edkmsbrand-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=edkmsbrand-cassandra
    edkmsbrand-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: edkmsbrand-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
